AWSTemplateFormatVersion: '2010-09-09'
Description: Bloomex QA Automation On-Demand (viewer + ALB + runner trigger). Clean template.

Parameters:
  ProjectName:
    Type: String
    Default: bloomex-qa-automation
    Description: Project tag prefix for all resources.
  EnvironmentName:
    Type: String
    Default: nonprod
    AllowedValues: [nonprod, prod]
    Description: Environment tag.
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC to host the ALB and EC2 instances.
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: At least two public subnets in different AZs for ALB and EC2.
  ViewerInstanceType:
    Type: String
    Default: t3.small
    Description: Instance type for always-on report viewer.
  ViewerAmiId:
    Type: AWS::EC2::Image::Id
    Description: AMI for the viewer EC2.
  KeyPairName:
    Type: String
    Default: ""
    Description: Optional key pair for EC2 troubleshooting (leave empty to disable SSH).
  ArtifactBucketName:
    Type: String
    Description: Existing S3 bucket containing automation-artifact.zip (you already created this).
  ArtifactZipKey:
    Type: String
    Default: automation-artifact.zip
    Description: Key in ArtifactBucketName for the artifact zip.
  ReportsBucketName:
    Type: String
    Description: Existing S3 bucket for reports (Allure history + last runs). Viewer syncs from this bucket.
  RunnerAmiId:
    Type: AWS::EC2::Image::Id
    Description: AMI for the on-demand runner EC2.
  RunnerDefaultInstanceType:
    Type: String
    Default: c7i.2xlarge
    Description: Default compute for on-demand runner.
  QacaToken:
    Type: String
    NoEcho: true
    Description: Shared token required by the trigger Lambda.

Conditions:
  HasKeyPair: !Not [!Equals [!Ref KeyPairName, ""]]

Resources:
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${ProjectName}-${EnvironmentName}-alb-sg"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-alb-sg"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref EnvironmentName


  ViewerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ALB to reach viewer
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref AlbSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
    
  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Type: application
      IpAddressType: ipv4
      Subnets: !Ref PublicSubnets
      SecurityGroups:
        - !Ref AlbSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-alb"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref EnvironmentName



  AlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      Matcher:
        HttpCode: "200-399"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-viewer-tg"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref EnvironmentName

  
  AlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Alb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AlbTargetGroup

  ViewerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ViewerS3ReportsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${ReportsBucketName}"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub "arn:aws:s3:::${ReportsBucketName}/*"
        - PolicyName: ViewerElbRegister
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - elasticloadbalancing:RegisterTargets
                  - elasticloadbalancing:DeregisterTargets
                Resource: "*"
        - PolicyName: ViewerLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  ViewerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ViewerRole

  ViewerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ViewerAmiId
      InstanceType: !Ref ViewerInstanceType
      SubnetId: !Select [0, !Ref PublicSubnets]
      SecurityGroupIds:
        - !Ref ViewerSecurityGroup
      IamInstanceProfile: !Ref ViewerInstanceProfile
      KeyName: !If [HasKeyPair, !Ref KeyPairName, !Ref "AWS::NoValue"]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euxo pipefail

          dnf -y update
          dnf -y install nginx awscli jq
          systemctl enable nginx
          systemctl start nginx

          # Pull QA UI page from artifact bucket
          aws s3 cp s3://${ArtifactBucketName}/qaautomation.html /usr/share/nginx/html/qaautomation.html || true
          cp -f /usr/share/nginx/html/qaautomation.html /usr/share/nginx/html/index.html || true

          mkdir -p /usr/share/nginx/html/reports
          cat >/etc/nginx/conf.d/reports.conf <<'EOF'
          server {
            listen 80 default_server;
            server_name _;
            root /usr/share/nginx/html;
            location / {
              try_files $uri $uri/ =404;
            }
          }
          EOF
          nginx -t && systemctl restart nginx

          # Register this instance into the ALB target group
          IID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
          aws elbv2 register-targets --region ${AWS::Region} --target-group-arn ${AlbTargetGroup} --targets Id=$IID,Port=80 || true

          # Initial sync
          aws s3 sync s3://${ReportsBucketName}/reports/ /usr/share/nginx/html/reports/ --delete || true

          # Cron: refresh every 2 minutes (reports + UI)
          cat >/etc/cron.d/qaca-sync <<EOF
          */2 * * * * root aws s3 sync s3://${ReportsBucketName}/reports/ /usr/share/nginx/html/reports/ --delete >/var/log/reports-sync.log 2>&1
          */2 * * * * root aws s3 cp s3://${ArtifactBucketName}/qaautomation.html /usr/share/nginx/html/qaautomation.html >/var/log/qaui-sync.log 2>&1
          EOF

  RunnerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Runner outbound only
      VpcId: !Ref VpcId
      SecurityGroupIngress: []
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  RunnerInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: RunnerS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: [s3:GetObject, s3:ListBucket]
                Resource:
                  - !Sub "arn:aws:s3:::${ArtifactBucketName}"
                  - !Sub "arn:aws:s3:::${ArtifactBucketName}/*"
              - Effect: Allow
                Action: [s3:PutObject, s3:DeleteObject, s3:GetObject, s3:ListBucket]
                Resource:
                  - !Sub "arn:aws:s3:::${ReportsBucketName}"
                  - !Sub "arn:aws:s3:::${ReportsBucketName}/*"
        - PolicyName: RunnerSelfTerminate
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: [ec2:TerminateInstances, ec2:StopInstances, ec2:DescribeInstances]
                Resource: "*"
        - PolicyName: RunnerLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: [logs:CreateLogGroup, logs:CreateLogStream, logs:PutLogEvents]
                Resource: "*"

  RunnerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref RunnerInstanceRole

  TriggerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TriggerRunInstances
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:RunInstances
                  - ec2:CreateTags
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeInstances
                Resource: "*"
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt RunnerInstanceRole.Arn
              - Effect: Allow
                Action: [logs:CreateLogGroup, logs:CreateLogStream, logs:PutLogEvents]
                Resource: "*"

  TriggerLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt TriggerLambdaRole.Arn
      Timeout: 60
      Environment:
        Variables:
          QACA_TOKEN: !Ref QacaToken
          ARTIFACT_BUCKET: !Ref ArtifactBucketName
          ARTIFACT_KEY: !Ref ArtifactZipKey
          REPORTS_BUCKET: !Ref ReportsBucketName
          RUNNER_AMI: !Ref RunnerAmiId
          RUNNER_SG: !Ref RunnerSecurityGroup
          SUBNETS: !Join [",", !Ref PublicSubnets]
          RUNNER_TYPE: !Ref RunnerDefaultInstanceType
        Code:
          ZipFile: |
            import json
            import os
            import boto3

            ec2 = boto3.client("ec2")


            def handler(event, ctx):
                tok = os.environ.get("QACA_TOKEN", "")
                headers = event.get("headers") or {}
                if tok and (headers.get("x-qaca-token") or headers.get("X-Qaca-Token") or "") != tok:
                    return {
                        "statusCode": 403,
                        "headers": {"content-type": "application/json"},
                        "body": json.dumps({"message": "Forbidden"}),
                    }

                body = event.get("body") or "{}"
                if isinstance(body, str):
                    try:
                        payload = json.loads(body)
                    except Exception:
                        payload = {}
                else:
                    payload = body or {}

                artifact = payload.get("artifact_s3_uri") or f"s3://{os.environ['ARTIFACT_BUCKET']}/{os.environ['ARTIFACT_KEY']}"
                env = payload.get("env", "nonprod")
                locale = payload.get("locale", "en")
                group_id = payload.get("groupId", "QAATG01")
                reports_prefix = payload.get("reportsPrefix") or f"reports/{env}/{locale}/{group_id}"

                user_data = f"""#!/bin/bash
            set -eux
            yum -y install awscli unzip || dnf -y install awscli unzip || true
            mkdir -p /opt/qaca && cd /opt/qaca
            aws s3 cp {artifact} a.zip
            unzip -o a.zip
            chmod +x run.sh || true
            REPORTS_BUCKET={os.environ['REPORTS_BUCKET']} REPORTS_PREFIX={reports_prefix} ENV_NAME={env} LOCALE={locale} GROUP_ID={group_id} ./run.sh || true
            shutdown -h now
            """

                subnets = os.environ["SUBNETS"].split(",")
                response = ec2.run_instances(
                    ImageId=os.environ["RUNNER_AMI"],
                    InstanceType=os.environ.get("RUNNER_TYPE", "c7i.2xlarge"),
                    MinCount=1,
                    MaxCount=1,
                    SubnetId=subnets[0],
                    SecurityGroupIds=[os.environ["RUNNER_SG"]],
                    UserData=user_data,
                    TagSpecifications=[
                        {
                            "ResourceType": "instance",
                            "Tags": [{"Key": "Name", "Value": "qa-runner"}],
                        }
                    ],
                )
                instance_id = response["Instances"][0]["InstanceId"]
                return {
                    "statusCode": 200,
                    "headers": {"content-type": "application/json"},
                    "body": json.dumps({"message": "runner launched", "instanceId": instance_id}),
                }

  TriggerFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: 'NONE'
      TargetFunctionArn: !GetAtt TriggerLambda.Arn
      Cors:
        AllowOrigins:
          - "*"
        AllowMethods:
          - "POST"
          - "OPTIONS"
        AllowHeaders:
          - "content-type"
          - "x-qaca-token"

  TriggerUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt TriggerLambda.Arn
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: 'NONE'

Outputs:
  AlbDnsName:
    Description: ALB DNS name for report viewer
    Value: !GetAtt Alb.DNSName
  TriggerUrl:
    Description: Function URL to trigger a runner launch
    Value: !GetAtt TriggerFunctionUrl.FunctionUrl
  ReportsBucketNameOut:
    Description: Reports bucket used by viewer and runner
    Value: !Ref ReportsBucketName
  ArtifactBucketNameOut:
    Description: Artifact bucket containing automation-artifact.zip
    Value: !Ref ArtifactBucketName
