AWSTemplateFormatVersion: '2010-09-09'
Description: Bloomex QA Automation On-Demand (viewer + ALB + runner trigger). Clean template.

Parameters:
  ProjectName:
    Type: String
    Default: bloomex-qa-automation
    Description: Project tag prefix for all resources.
  EnvironmentName:
    Type: String
    Default: nonprod
    AllowedValues: [nonprod, prod]
    Description: Environment tag.
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC to host the ALB and EC2 instances.
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: At least two public subnets in different AZs for ALB and EC2.
  ViewerInstanceType:
    Type: String
    Default: t3.small
    Description: Instance type for always-on report viewer.
  ViewerAmiId:
    Type: AWS::EC2::Image::Id
    Description: AMI for the viewer EC2.
  KeyPairName:
    Type: String
    Default: ""
    Description: Optional key pair for EC2 troubleshooting (leave empty to disable SSH).
  ArtifactBucketName:
    Type: String
    Description: Existing S3 bucket containing automation-artifact.zip (you already created this).
  ArtifactZipKey:
    Type: String
    Default: automation-artifact.zip
    Description: Key in ArtifactBucketName for the artifact zip.
  ReportsBucketName:
    Type: String
    Description: Existing S3 bucket for reports (Allure history + last runs). Viewer syncs from this bucket.
  RunnerAmiId:
    Type: AWS::EC2::Image::Id
    Description: AMI for the on-demand runner EC2.
  RunnerDefaultInstanceType:
    Type: String
    Default: c7i.2xlarge
    Description: Default compute for on-demand runner.
  QacaToken:
    Type: String
    NoEcho: true
    Description: Shared token required by the trigger Lambda.

Conditions:
  HasKeyPair: !Not [!Equals [!Ref KeyPairName, ""]]

Resources:
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${ProjectName}-${EnvironmentName}-alb-sg"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-as"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref EnvironmentName

  ViewerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ALB to reach viewer
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref AlbSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-viewer-sg"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref EnvironmentName

  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Type: application
      IpAddressType: ipv4
      Subnets: !Ref PublicSubnets
      SecurityGroups:
        - !Ref AlbSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-lb"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref EnvironmentName

  AlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      Matcher:
        HttpCode: "200-399"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-tg"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref EnvironmentName

  AlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Alb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AlbTargetGroup

  ViewerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ViewerS3ReportsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${ReportsBucketName}"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub "arn:aws:s3:::${ReportsBucketName}/*"
        - PolicyName: ViewerElbRegister
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - elasticloadbalancing:RegisterTargets
                  - elasticloadbalancing:DeregisterTargets
                Resource: "*"
        - PolicyName: ViewerLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref EnvironmentName

  ViewerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ViewerRole

  ViewerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ViewerAmiId
      InstanceType: !Ref ViewerInstanceType
      SubnetId: !Select [0, !Ref PublicSubnets]
      SecurityGroupIds:
        - !Ref ViewerSecurityGroup
      IamInstanceProfile: !Ref ViewerInstanceProfile
      KeyName: !If [HasKeyPair, !Ref KeyPairName, !Ref "AWS::NoValue"]
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-viewer"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref EnvironmentName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euxo pipefail

          dnf -y update
          dnf -y install nginx awscli jq
          systemctl enable nginx
          systemctl start nginx
	  # Pull QA UI page from artifact bucket
	  aws s3 cp s3://${ArtifactBucketName}/qaautomation.html /usr/share/nginx/html/qaautomation.html || true
	  cp -f /usr/share/nginx/html/qaautomation.html /usr/share/nginx/html/index.html || true

          mkdir -p /usr/share/nginx/html/reports
          cat >/etc/nginx/conf.d/reports.conf <<'EOF'
          server {
            listen 80 default_server;
            server_name _;
            root /usr/share/nginx/html;
            location / {
              try_files $uri $uri/ =404;
            }
          }
          EOF
          nginx -t && systemctl restart nginx

          # Register this instance into the ALB target group (breaks CFN dependency cycles)
          IID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
          aws elbv2 register-targets --region ${AWS::Region} --target-group-arn ${AlbTargetGroup} --targets Id=$IID,Port=80 || true

          # Sync reports from S3 (Allure history / last runs)
          aws s3 sync s3://${ReportsBucketName}/reports/ /usr/share/nginx/html/reports/ --delete || true
	  */2 * * * * root aws s3 cp s3://${ArtifactBucketName}/qaautomation.html /usr/share/nginx/html/qaautomation.html >/var/log/qaui-sync.log 2>&1

          # Cron: refresh every 2 minutes
          cat >/etc/cron.d/reports-sync <<EOF
          */2 * * * * root aws s3 sync s3://${ReportsBucketName}/reports/ /usr/share/nginx/html/reports/ --delete >/var/log/reports-sync.log 2>&1
          EOF

  RunnerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Runner outbound only
      VpcId: !Ref VpcId
      SecurityGroupIngress: []
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-runner-sg"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref EnvironmentName

  RunnerInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: RunnerS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: [s3:GetObject, s3:ListBucket]
                Resource:
                  - !Sub "arn:aws:s3:::${ArtifactBucketName}"
                  - !Sub "arn:aws:s3:::${ArtifactBucketName}/*"
              - Effect: Allow
                Action: [s3:PutObject, s3:DeleteObject, s3:GetObject, s3:ListBucket]
                Resource:
                  - !Sub "arn:aws:s3:::${ReportsBucketName}"
                  - !Sub "arn:aws:s3:::${ReportsBucketName}/*"
        - PolicyName: RunnerSelfTerminate
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: [ec2:TerminateInstances, ec2:StopInstances, ec2:DescribeInstances]
                Resource: "*"
        - PolicyName: RunnerLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: [logs:CreateLogGroup, logs:CreateLogStream, logs:PutLogEvents]
                Resource: "*"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref EnvironmentName

  RunnerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref RunnerInstanceRole

  TriggerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TriggerRunInstances
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:RunInstances
                  - ec2:CreateTags
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeInstances
                Resource: "*"
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt RunnerInstanceRole.Arn
              - Effect: Allow
                Action: [logs:CreateLogGroup, logs:CreateLogStream, logs:PutLogEvents]
                Resource: "*"

  TriggerLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt TriggerLambdaRole.Arn
      Timeout: 30
      Environment:
        Variables:
          STAGING_BUCKET: !Ref ReportsBucketName
          ARTIFACT_BUCKET: !Ref ArtifactBucketName
          ARTIFACT_KEY: !Ref ArtifactZipKey
          REPORTS_BUCKET: !Ref ReportsBucketName
          ENV_NAME: !Ref EnvironmentName
          RUNNER_AMI: !Ref RunnerAmiId
          RUNNER_INSTANCE_PROFILE: !GetAtt RunnerInstanceProfile.Arn
          RUNNER_SECURITY_GROUP: !Ref RunnerSecurityGroup
          RUNNER_SUBNET: !Select [0, !Ref PublicSubnets]
          DEFAULT_INSTANCE_TYPE: !Ref RunnerDefaultInstanceType
          VIEWER_BASE_URL: !Sub "http://${Alb.DNSName}"
          QACA_TOKEN: !Ref QacaToken
      Code:
        ZipFile: |
          import json, os, textwrap, boto3
          ec2 = boto3.client("ec2")

          def _cors_headers():
              return {
                  "access-control-allow-origin": "*",
                  "access-control-allow-headers": "content-type, x-qaca-token",
                  "access-control-allow-methods": "POST, OPTIONS",
              }

          def handler(event, context):
              method = (((event or {}).get("requestContext") or {}).get("http") or {}).get("method", "").upper()
              if method == "OPTIONS":
                  return {
                      "statusCode": 200,
                      "headers": _cors_headers(),
                      "body": "",
                  }

              headers = {k.lower(): v for k, v in ((event or {}).get("headers") or {}).items()}
              provided = headers.get("x-qaca-token", "")
              expected = os.environ.get("QACA_TOKEN", "")
              if not provided or provided != expected:
                  return {
                      "statusCode": 401,
                      "headers": _cors_headers() | {"content-type": "application/json"},
                      "body": json.dumps({"message": "Unauthorized"}),
                  }

              body = {}
              if isinstance(event, dict) and event.get("body"):
                  try:
                      body = json.loads(event["body"])
                  except Exception:
                      body = {}
              itype = body.get("instanceType") or os.environ["DEFAULT_INSTANCE_TYPE"]

              artifact_path = body.get("artifactPath") or ""
              if artifact_path.startswith("s3://"):
                  normalized_artifact = artifact_path
              else:
                  key = body.get("artifactKey") or os.environ["ARTIFACT_KEY"]
                  normalized_key = key[1:] if key.startswith("/") else key
                  bucket = os.environ["ARTIFACT_BUCKET"].removeprefix("s3://").rstrip("/")
                  normalized_artifact = f"s3://{bucket}/{normalized_key}"

              staging_bucket = body.get("stagingBucket") or os.environ.get("STAGING_BUCKET", "")
              env_name = body.get("env") or os.environ.get("ENV_NAME", "nonprod")
              locale = body.get("locale") or os.environ.get("LOCALE", "en")
              group_id = body.get("groupId") or os.environ.get("GROUP_ID", "QAATG01")
              execution_id = body.get("executionId") or getattr(context, "aws_request_id", "") or "manual"
              reports_prefix = body.get("reportsPrefix") or f"reports/{env_name}/{locale}/{group_id}"
              reports_bucket = os.environ["REPORTS_BUCKET"]
              region = os.environ.get("AWS_REGION", "")

              user_data = textwrap.dedent(
                  f"""
                  #!/bin/bash
                  set -euxo pipefail
                  dnf -y update
                  dnf -y install awscli unzip
                  cd /root
                  export ARTIFACT_PATH=\"{normalized_artifact}\"
                  export STAGING_BUCKET=\"{staging_bucket}\"
                  export EXECUTION_ID=\"{execution_id}\"
                  export ENV_NAME=\"{env_name}\"
                  export LOCALE=\"{locale}\"
                  export GROUP_ID=\"{group_id}\"
                  export REPORTS_PREFIX=\"{reports_prefix}\"
                  ARTIFACT_SOURCE="$ARTIFACT_PATH"
                  if [[ ! $ARTIFACT_SOURCE =~ ^s3:// ]]; then
                    ARTIFACT_SOURCE="s3://"${{ARTIFACT_SOURCE#s3://}}
                  fi
                  aws s3 cp "$ARTIFACT_SOURCE" /root/artifact.zip
                  unzip -o /root/artifact.zip -d /root/qaca
                  # TODO: run your runner script here.
                  # Example: cd /root/qaca && ./run.sh || true
                  # TODO: upload results to reports bucket.
                  # Example: aws s3 sync /root/qaca/allure-report s3://{reports_bucket}/reports/latest/ --delete || true
                  IID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
                  aws ec2 terminate-instances --instance-ids $IID --region {region} || shutdown -h now
                  """
              ).lstrip()

              resp = ec2.run_instances(
                  ImageId=os.environ["RUNNER_AMI"],
                  InstanceType=itype,
                  MinCount=1,
                  MaxCount=1,
                  IamInstanceProfile={"Arn": os.environ["RUNNER_INSTANCE_PROFILE"]},
                  NetworkInterfaces=[{
                      "DeviceIndex": 0,
                      "SubnetId": os.environ["RUNNER_SUBNET"],
                      "Groups": [os.environ["RUNNER_SECURITY_GROUP"]],
                      "AssociatePublicIpAddress": True
                  }],
                  UserData=user_data,
                  TagSpecifications=[{
                      "ResourceType": "instance",
                      "Tags": [{"Key":"Name","Value":"qa-runner"},{"Key":"Project","Value":"qaca"}]
                  }]
              )
              iid = resp["Instances"][0]["InstanceId"]
              return {
                  "statusCode": 200,
                  "headers": _cors_headers() | {"content-type":"application/json"},
                  "body": json.dumps({"message":"runner launched","instanceId": iid, "instanceType": itype})
              }

  TriggerFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref TriggerLambda
      Cors:
        AllowOrigins:
          - "*"
        AllowMethods:
          - "POST"
          - "OPTIONS"
        AllowHeaders:
          - "content-type"
          - "x-qaca-token"

  TriggerUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TriggerLambda
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

Outputs:
  AlbDnsName:
    Description: ALB DNS name for report viewer
    Value: !GetAtt Alb.DNSName
  TriggerUrl:
    Description: Function URL to trigger a runner launch
    Value: !GetAtt TriggerFunctionUrl.FunctionUrl
  ReportsBucketNameOut:
    Description: Reports bucket used by viewer and runner
    Value: !Ref ReportsBucketName
  ArtifactBucketNameOut:
    Description: Artifact bucket containing automation-artifact.zip
    Value: !Ref ArtifactBucketName
